### PR TITLE
fix: strip HTML tags from plaintext search result descriptions

### LINKED ISSUE #1681: Raw HTML rendering in search results
### Describe the bug

Compare page:
Raw HTML rendering in package search results instead of parsed or sanitized content.

Image

### PR DESCRIPTION
**Pull request by serhalp**
### 🔗 Linked issue

Fixes #1681

### 🧭 Context

Probably a regression from https://github.com/npmx-dev/npmx.dev/pull/1582

### 📚 Description

After decoding HTML entities, descriptions containing entity-encoded HTML (e.g. `&lt;a&gt;`) were displaying reconstructed tags as raw text. Apply `stripHtmlTags` after `decodeHtmlEntities` in `PackageSelector` and `TableRow` components.

Screenshot 2026-02-27 at 09 00 42

### CODE REVIEW

File: shared/utils/html.ts [hunk 1]
```diff
@@ -11,3 +11,7 @@
 export function decodeHtmlEntities(text: string): string {
   return text.replace(/&(?:amp|lt|gt|quot|apos|nbsp|#39);/g, match => htmlEntities[match] || match)
 }
+
+export function stripHtmlTags(text: string): string {
+  return text.replace(/<[^>]*>/g, '')
```
[the remark this answers is not in the document]
Comment (serhalp) [reply shared/utils/html.ts]: I think this is not worth addressing. Using sanitize-html in the client would add 50 KB to the bundle(?) and vue's sanitization already protects us here. Yeah?

File: shared/utils/html.ts [hunk 2]
```diff
@@ -11,3 +11,7 @@ const htmlEntities: Record<string, string> = {
 export function decodeHtmlEntities(text: string): string {
   return text.replace(/&(?:amp|lt|gt|quot|apos|nbsp|#39);/g, match => htmlEntities[match] || match)
 }
+
+export function stripHtmlTags(text: string): string {
```
Comment (danielroe) [inline shared/utils/html.ts:20]: I believe we already have this code somewhere in the code base. We don't need to create a new function.

File: app/components/Package/TableRow.vue [hunk 3]
```diff
@@ -69,7 +69,7 @@ const allMaintainersText = computed(() => {
       v-if="isColumnVisible('description')"
       class="py-2 px-3 text-sm text-fg-muted max-w-xs truncate"
     >
-      {{ decodeHtmlEntities(pkg.description || '-') }}
+      {{ stripHtmlTags(decodeHtmlEntities(pkg.description || '-')) }}
```
Comment (vmrjnvc) [inline app/components/Package/TableRow.vue:72]: now with this changes there could be full empty descriptions displayed, but there should be dash if there is no description

Image

so correct should be `{{ stripHtmlTags(decodeHtmlEntities(pkg.description || '')) || '-'}}` because if there is just html in the description, all will be removed and we don't have fallback

Comment (serhalp) [reply app/components/Package/TableRow.vue:72]: good catch! would you like to open a quick PR for that? 🙏🏼

Comment (vmrjnvc) [reply app/components/Package/TableRow.vue:72]: sure, no problem!

here https://github.com/npmx-dev/npmx.dev/pull/1763
