### PR TITLE
fix: add date in chart tooltip

### LINKED ISSUE #1815: Compare: Improve chart UX
### Describe the feature

Really small QoL change for the compare graphs

Currently, the 'hovered' date is only shown on the x axis line. Which means, when naturally seeking through the graph, the results box overlaps it.

Image

Image

Would be nice to have this instead, with the current hovered date embedded in the results box

Image

I'd love to help out in implementing, but don't think I'll find the time anytime soon. Alas, it's very low priority :P 

### Additional information

- [x] Would you be willing to help implement this feature?

### Final checks

- [x] Read the [contribution guide](https://github.com/npmx-dev/npmx.dev/blob/main/CONTRIBUTING.md).
- [x] Check existing [issues](https://github.com/npmx-dev/npmx.dev/issues).

### PR DESCRIPTION
**Pull request by RYGRIT**
### 🔗 Linked issue

resolves #1815 

### 📚 Description

| before | after |
| --- | --- |
| image | image |

### CODE REVIEW

File: app/components/Package/TrendsChart.vue [hunk 1]
```diff
@@ -1598,11 +1609,23 @@ const chartConfig = computed<VueUiXyConfig>(() => {
         borderColor: 'transparent',
         backdropFilter: false,
         backgroundColor: 'transparent',
-        customFormat: ({ datapoint: items }) => {
+        customFormat: ({ datapoint: items, absoluteIndex }) => {
```
[the remark this answers is not in the document]
Comment (RYGRIT) [reply app/components/Package/TrendsChart.vue:1612]: The `customFormat` implementation in `VersionDistribution.vue` that I referenced has been tested locally and doesn't seem to have the problem you mentioned.

File: app/components/Package/TrendsChart.vue [hunk 2]
```diff
@@ -1598,11 +1609,23 @@ const chartConfig = computed<VueUiXyConfig>(() => {
...
           if (!items || pending.value) return ''
 
           const hasMultipleItems = items.length > 1
 
+          // Format date for compare page (multi-package mode, not in modal)
+          let formattedDate = ''
+          if (!props.inModal && hasMultipleItems && absoluteIndex !== undefined) {
```
Comment (graphieros) [inline app/components/Package/TrendsChart.vue]: I think just checking if `hasMultipleItems` and valid `absoluteIndex` is enough. You never know in the future if we display this chart for multiple series in a modal.

Comment (RYGRIT) [reply app/components/Package/TrendsChart.vue]: Yes, you're right. I need to rest now. I'll fix it later.

Comment (graphieros) [reply app/components/Package/TrendsChart.vue]: Oh please do rest :)
I'll do it

Comment (RYGRIT) [reply app/components/Package/TrendsChart.vue]: Thanks!
