### PR TITLE
fix: polish versions layout

### LINKED ISSUE #532: Peer dependency versions cut off on mobile

### PR DESCRIPTION
**Pull request by alexdln**
A minor revision and improvement of another PR (#549 ) based on what was discussed and implemented in the previous PR.

I've finalized the overall layout. Each version can take up a maximum of 40% of the page. If possible, the version is not cropped, but the title is. If neither fits, both are cropped. Content is always at the edges.

I also removed the span between the name and version. I see it was added during the RTL improvements, but I checked that everything looks great in RTL without it now.

The layout on the mobile version has also improved

Example with optional deps - [vitest](https://npmx.dev/vitest)

Closes #532
closes #549

### CODE REVIEW

File: app/components/PackageDependencies.vue [hunk 1]
```diff
@@ -188,19 +187,20 @@ const sortedOptionalDependencies = computed(() => {
...
-              class="px-1 py-0.5 font-mono text-[10px] text-fg-subtle bg-bg-muted border border-border rounded shrink-0"
+              class="shrink-0 text-fg-muted hover:text-fg transition-colors duration-200 cursor-help inline-flex items-center"
               :title="$t('package.dependencies.optional')"
+              :aria-label="$t('package.dependencies.optional')"
+              role="img"
             >
-              {{ $t('package.dependencies.optional') }}
+              <span aria-hidden="true" class="i-carbon:information w-3 h-3 block" />
             </span>
           </div>
```
Comment (alexdln) [inline app/components/PackageDependencies.vue:195]: Hmm, that's not mine 👀

Comment (danielroe) [reply app/components/PackageDependencies.vue:195]: wdym?

Comment (alexdln) [reply app/components/PackageDependencies.vue:195]: I'm not sure if this was agreed. I can revert it and the author might do an additional MR for this part

Please tell what works best for you

File: app/components/PackageDependencies.vue [hunk 2]
```diff
@@ -188,19 +187,20 @@ const sortedOptionalDependencies = computed(() => {
             </NuxtLink>
             <span
               v-if="peer.optional"
-              class="px-1 py-0.5 font-mono text-[10px] text-fg-subtle bg-bg-muted border border-border rounded shrink-0"
+              class="shrink-0 text-fg-muted hover:text-fg transition-colors duration-200 cursor-help inline-flex items-center"
               :title="$t('package.dependencies.optional')"
+              :aria-label="$t('package.dependencies.optional')"
```
Comment (danielroe) [inline app/components/PackageDependencies.vue]: this was included in the other PR

I think the current `?` icon isn't sufficient to communicate a peer dep is optional, and we should either choose another icon or keep the badge

File: app/components/PackageDependencies.vue (hunk 1 above)
Comment (danielroe) [reply app/components/PackageDependencies.vue:195]: understood - added a comment

File: app/components/PackageDependencies.vue (hunk 2 above)
Comment (alexdln) [reply app/components/PackageDependencies.vue]: Meanwhile, an icon is used for outdated deps, and it seems useful to standardize them. But I don't even know what icon would be appropriate (_if an icon is used in one place to indicate a dependency specifics, it is useful to use icons everywhere in such cases_). I agree that the "?" is indeed read as a tooltip 🤔

Comment (alexdln) [reply app/components/PackageDependencies.vue]: So, I think I'll revert to the way it was and create an additional issue. I hope we would find a suitable one there

Comment (danielroe) [reply app/components/PackageDependencies.vue]: agreed. for now, let's revert this change and then we can open a new PR to update/align icons

Comment (alexdln) [reply app/components/PackageDependencies.vue]: Done, thanks!

(_Just for history - issue for icons - #628_)
