### PR TITLE
fix(i18n): force install command direction to `'ltr'`

### LINKED ISSUE #1051: Installation commands should have `dir="auto"` or `dir="ltr"`
For RTL languages (Arabic), we display the block with installation commands it RTL. Setting direction to `auto` should fix that, but in my opinion it makes more sense to set the direction to `ltr`, since installation commands will always be in English.
Would love to hear opinions on this.

<details>
<summary>Current</summary>
Image
</details>

<details>
<summary>Proposed</summary>
Image
</details>

### PR DESCRIPTION
**Pull request by BobbieGoede**
Resolves #1051 

If there are more commands rendered somewhere let me know.

image

### CODE REVIEW

**Comment by DDeenis** [comment]
LGTM 👍

**Comment by BobbieGoede** [comment]
needs some tweaks
image

@DDeenis what would be the best way to deal with the comments here?

**Comment by DDeenis** [comment]
I would say, ideally they should be auto since they can be Arabic?

**Comment by DDeenis** [comment]
Let's try this - commands always LTR, comments `auto`

**Comment by BobbieGoede** [comment]
@DDeenis 
image

**Comment by DDeenis** [comment]
Nice! That looks really good

File: app/components/Terminal/Install.vue [hunk 1]
```diff
@@ -104,7 +104,7 @@ const copyCreateCommand = () => copyCreate(getFullCreateCommand())
         <span class="w-2.5 h-2.5 rounded-full bg-fg-subtle" />
         <span class="w-2.5 h-2.5 rounded-full bg-fg-subtle" />
       </div>
-      <div class="px-3 pt-2 pb-3 sm:px-4 sm:pt-3 sm:pb-4 space-y-1 overflow-x-auto">
+      <div class="px-3 pt-2 pb-3 sm:px-4 sm:pt-3 sm:pb-4 space-y-1 overflow-x-auto" dir="auto">
```
[the remark this answers is not in the document]
Comment (BobbieGoede) [reply app/components/Terminal/Install.vue]: is `dir` not inherited from its parents?

**Comment by DDeenis** [comment]
Note - we are waiting for a confirmation from a person who speaks Arabic

File: app/components/Terminal/Install.vue [hunk 2]
```diff
@@ -104,7 +104,7 @@ const copyCreateCommand = () => copyCreate(getFullCreateCommand())
         <span class="w-2.5 h-2.5 rounded-full bg-fg-subtle" />
         <span class="w-2.5 h-2.5 rounded-full bg-fg-subtle" />
       </div>
-      <div class="px-3 pt-2 pb-3 sm:px-4 sm:pt-3 sm:pb-4 space-y-1 overflow-x-auto">
+      <div class="px-3 pt-2 pb-3 sm:px-4 sm:pt-3 sm:pb-4 space-y-1 overflow-x-auto" dir="ltr">
```
Comment (serhalp) [inline app/components/Terminal/Install.vue:107]: This (and other others) might easily get mistakenly "fixed" in the future. Could we leave an explanatory comment on each one? or maybe a custom directive with an expressive name that just sets `dir="ltr"` could serve the same purpose? https://vuejs.org/guide/reusability/custom-directives

Comment (skaldebane) [reply app/components/Terminal/Install.vue:107]: Maybe something like `v-always-ltr`?
