### PR TITLE
fix(cli): use a shared cross-platform npm process resolver without shell

### LINKED ISSUE #2216: [BUG - cli win] DEP0190 deprecation warning
### Describe the bug

Running npmx-connector emits a Node.js DEP0190 deprecation warning when checking npm authentication

### Additional context

_No response_

### Logs

```shell-script
PS C:\\Users\\mynameistito> bunx npmx-connector

┌   npmx connector
│
▲  This allows npmx.dev to access your npm cli and any authenticated contexts.
│
◇  Do you accept?
│  Yes
│
●  Checking npm authentication...
(node:28304) \[DEP0190] DeprecationWarning: Passing args to a child process with shell option true can lead to security vulnerabilities, as the arguments are not escaped, only concatenated.

(Use `node --trace-deprecation ...` to show where the warning was created)
│
▲  Not logged in to npm. Starting npm login...

npm notice Log in on https://registry.npmjs.org/

Login at:

https://www.npmjs.com/login?next=/login/cli/UUID

Press ENTER to open in the browser...

Logged in on https://registry.npmjs.org/.

●  Authenticated as: mynameistito
│
◇  Click to connect ──────────────────────────────────────────────────────────╮
│                                                                             │
│  Open: https://npmx.dev/?token=<token>\&port=31415                          │
│                                                                             │
│  Or paste token manually: <token>                                           │
│                                                                             │
├─────────────────────────────────────────────────────────────────────────────╯

➜ Listening on: http://127.0.0.1:31415/
│
●  Waiting for connection... (Press Ctrl+C to stop)
Server closed successfully.
PS C:\\Users\\mynameistito>
```

### PR DESCRIPTION
**Pull request by MathurAditya724**
## Summary

Fixes the Windows connector auth flow while avoiding shell-based npm execution and DEP0190 warnings.

### What changed

- Added a shared npm process resolver in `cli/src/npm-process.ts`.
- Routed npm invocations through this resolver in:
  - `cli/src/cli.ts` (`npm login`)
  - `cli/src/npm-client.ts` (non-interactive npm exec + package publish path)
- Kept interactive PTY execution using `npm` directly.
- On Windows, npm now runs via `cmd.exe /d /s /c npm ...` (no `shell: true`, no direct `npm.cmd` spawn).
- Cleaned up an unused exported type to satisfy unused-code checks.

### Why

The previous approach removed DEP0190 warnings but caused Windows runtime failures (`spawn EINVAL`) in login flow.
Using a centralized, explicit cross-platform command resolver keeps behavior consistent and avoids shell-based execution.

Closes #2216

### CODE REVIEW

**Comment by mynameistito** [comment]
Dam I got nerd sniped!

Lmk if ya need a test on Windows (if you're not also on Windows / have a windows machine)

**Comment by MathurAditya724** [comment]
if you have a windows machine, go ahead, more the testers the better. I don't  have one, so was planning to ask my friend today evening, will mention how that went.

**Comment by mynameistito** [comment]
Checking it out now, are you in the discord? @MathurAditya724 

there is a few issues with your implementation.

**Comment by MathurAditya724** [comment]
yes, I'm `.n1ghtmare.`

**Comment by mynameistito** [comment]
As stated on Discord, the changes you made seemed to have caused some issues;
<details>
<summary>my output with your changes</summary>

```pwsh
PS F:\GitHub\temp\npmx.dev\cli> npmx-connector
┌   npmx connector
│
▲  This allows npmx.dev to access your npm cli and any authenticated contexts.
│
◇  Do you accept?
│  Yes
│
●  Checking npm authentication...
│
▲  Not logged in to npm. Starting npm login...

Error: spawn EINVAL
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:796:9)
    at file:///F:/GitHub/temp/npmx.dev/cli/dist/cli.mjs:16:17
    at new Promise (<anonymous>)
    at runNpmLogin (file:///F:/GitHub/temp/npmx.dev/cli/dist/cli.mjs:15:9)
    at Object.run (file:///F:/GitHub/temp/npmx.dev/cli/dist/cli.mjs:54:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:104:5)
    at async runCommand (file:///F:/GitHub/temp/npmx.dev/node_modules/.pnpm/citty@0.2.1/node_modules/
citty/dist/index.mjs:188:47)
    at async runMain (file:///F:/GitHub/temp/npmx.dev/node_modules/.pnpm/citty@0.2.1/node_modules/cit
ty/dist/index.mjs:285:10) {
  errno: -4071,
  code: 'EINVAL',
  syscall: 'spawn'
}
```

</details>

I asked Claude to fix up the issues and this was the Fix that the model proposed and I tested it manually and seems to work as intended;

<details>
<summary>Fix suggested by Claude Opus 4.6</summary>
Lines 15, through 21

```diff
// ~/cli.ts
-const NPM_COMMAND = process.platform === 'win32' ? 'npm.cmd' : 'npm'
-
 async function runNpmLogin(): Promise<boolean> {
   return new Promise(resolve => {
-    const child = spawn(NPM_COMMAND, ['login', `--registry=${NPM_REGISTRY_URL}`], {
-      stdio: 'inherit',
-    })
+
+    const loginArgs = ['login', `--registry=${NPM_REGISTRY_URL}`]
+    const child =
+      process.platform === 'win32'
+        ? spawn('cmd.exe', ['/c', 'npm', ...loginArgs], { stdio: 'inherit' })
+        : spawn('npm', loginArgs, { stdio: 'inherit' })
```

</details>

Routing through `cmd.exe /c npm` on Windows avoids both `EINVAL` and the DEP0190 warning — no `.cmd` file is spawned directly, and no `shell: true` is needed.


Might be good to get some more eyes on it though.

**Comment by mynameistito** [comment]
Seems to work as intended now;
## Whilst Logged in to npmjs;
```pwsh
PS F:\GitHub\temp\npmx.dev\cli> bun run build
$ tsdown
ℹ tsdown v0.21.4 powered by rolldown v1.0.0-rc.9
ℹ config file: F:\GitHub\temp\npmx.dev\cli\tsdown.config.ts
ℹ entry: src\index.ts, src\cli.ts
ℹ target: node24.0.0
ℹ tsconfig: tsconfig.json

 WARN  `external` is deprecated. Use `deps.neverBundle` instead.

ℹ Build start
ℹ Granting execute permission to dist\cli.mjs
ℹ dist\cli.mjs                       2.62 kB │ gzip:  1.23 kB
ℹ dist\index.mjs                     0.17 kB │ gzip:  0.14 kB
ℹ dist\server-FP9KQp94.mjs.map      81.93 kB │ gzip: 18.58 kB
ℹ dist\server-FP9KQp94.mjs          40.86 kB │ gzip:  9.61 kB
ℹ dist\cli.mjs.map                   4.53 kB │ gzip:  1.91 kB
ℹ dist\index.d.mts.map               2.16 kB │ gzip:  0.67 kB
ℹ dist\node-pty-PmtOFpde.d.mts.map   1.45 kB │ gzip:  0.65 kB
ℹ dist\index.d.mts                   5.20 kB │ gzip:  1.60 kB
ℹ dist\cli.d.mts                     0.01 kB │ gzip:  0.03 kB
ℹ dist\node-pty-PmtOFpde.d.mts       1.52 kB │ gzip:  0.59 kB
ℹ 10 files, total: 140.45 kB
✔ Build complete in 678ms
PS F:\GitHub\temp\npmx.dev\cli> bun install
bun install v1.3.11 (af24e281)

Checked 57 installs across 83 packages (no changes) [11.00ms]
PS F:\GitHub\temp\npmx.dev\cli> bun run build
$ tsdown
ℹ tsdown v0.21.4 powered by rolldown v1.0.0-rc.9
ℹ config file: F:\GitHub\temp\npmx.dev\cli\tsdown.config.ts
ℹ entry: src\index.ts, src\cli.ts
ℹ target: node24.0.0
ℹ tsconfig: tsconfig.json

 WARN  `external` is deprecated. Use `deps.neverBundle` instead.

ℹ Build start
ℹ Cleaning 11 files
ℹ Granting execute permission to dist\cli.mjs
ℹ dist\cli.mjs                       2.62 kB │ gzip:  1.23 kB
ℹ dist\index.mjs                     0.17 kB │ gzip:  0.14 kB
ℹ dist\server-FP9KQp94.mjs.map      81.93 kB │ gzip: 18.58 kB
ℹ dist\server-FP9KQp94.mjs          40.86 kB │ gzip:  9.61 kB
ℹ dist\cli.mjs.map                   4.53 kB │ gzip:  1.91 kB
ℹ dist\index.d.mts.map               2.16 kB │ gzip:  0.67 kB
ℹ dist\node-pty-PmtOFpde.d.mts.map   1.45 kB │ gzip:  0.65 kB
ℹ dist\index.d.mts                   5.20 kB │ gzip:  1.60 kB
ℹ dist\cli.d.mts                     0.01 kB │ gzip:  0.03 kB
ℹ dist\node-pty-PmtOFpde.d.mts       1.52 kB │ gzip:  0.59 kB
ℹ 10 files, total: 140.45 kB
✔ Build complete in 627ms
PS F:\GitHub\temp\npmx.dev\cli> bun link
bun link v1.3.11 (af24e281)
Success! Registered "npmx-connector"

To use npmx-connector in a project, run:
  bun link npmx-connector

Or add it in dependencies in your package.json file:
  "npmx-connector": "link:npmx-connector"
PS F:\GitHub\temp\npmx.dev\cli> npmx-connector
┌   npmx connector
│
▲  This allows npmx.dev to access your npm cli and any authenticated contexts.
│
◇  Do you accept?
│  Yes
│
●  Checking npm authentication...
│
●  Authenticated as: mynameistito
│
◇  Click to connect ──────────────────────────────────────────────────────────╮
│                                                                             │
│  Open: https://npmx.dev/?token=$TOKEN&port=31415  │
│                                                                             │
│  Or paste token manually: $TOKEN                  │
│                                                                             │
├─────────────────────────────────────────────────────────────────────────────╯
➜ Listening on: http://127.0.0.1:31415/
│
●  Waiting for connection... (Press Ctrl+C to stop)
Server closed successfully.
PS F:\GitHub\temp\npmx.dev\cli>
```
## Without being logged into npmjs;

```pwsh
PS F:\GitHub\temp\npmx.dev\cli> npmx-connector
┌   npmx connector
│
▲  This allows npmx.dev to access your npm cli and any authenticated contexts.
│
◇  Do you accept?
│  Yes
│
●  Checking npm authentication...
│
▲  Not logged in to npm. Starting npm login...

npm notice Log in on https://registry.npmjs.org/
Login at:
https://www.npmjs.com/login?next=/login/cli/$UUID
Press ENTER to open in the browser...
/
```

However, there was an issue when trying to originally build on `src/server.ts` L 90 which doesnt seem to be related to your changes;

```diff
-export function createConnectorApp(expectedToken: string) {
+export function createConnectorApp(expectedToken: string): H3 {
```

**Comment by RYGRIT** [comment]
Thanks for tackling this!

Directly spawning `npm.cmd` on Windows isn’t safe — see Node.js issue [#58763](https://github.com/nodejs/node/issues/58763) and the docs: `.cmd`/`.bat` files can’t be executed directly on Windows, they need a shell. Using `args + shell: true` triggers DEP0190 because args are just space-joined.

I’d recommend using `cmd.exe /c npm ...` on Windows.

**Comment by MathurAditya724** [comment]
@RYGRIT just changed the approach, thanks to @mynameistito, and update the PR title and description to better reflect what we have done

File: cli/src/npm-process.ts [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+  npmArgs: string[],
+  platform = process.platform,
+  comSpec = process.env.ComSpec,
+): NpmProcessCommand {
+  if (platform === 'win32') {
+    return {
+      command: comSpec || 'cmd.exe',
+      args: ['/d', '/s', '/c', 'npm', ...npmArgs],
+    }
+  }
```
Comment (ghostdevv) [inline cli/src/npm-process.ts:18]: Are there any examples anyone is aware of, of other projects doing this? Just want to make sure, as not a windows user, this is the safest best way 😅

Comment (mynameistito) [reply cli/src/npm-process.ts:18]: unsure if it's the safest way, however am aware that it works as intended to minimise the DEP1090 Issue

Comment (RYGRIT) [reply cli/src/npm-process.ts:18]: Looked into this a bit more.

The two approaches I found were either:

- keep using a shell, but pass a single command string
- explicitly use `cmd.exe /d /s /c ...` on Windows

[Node-RED](https://github.com/node-red/node-red/pull/5207) took the first approach for the same deprecation, with the main change in [b364f8f](https://github.com/node-red/node-red/commit/b364f8f9b687aa005f2fd32a0fd1025e69693080). For this case though, I think the second one is the better fit. It is still consistent with Node’s Windows guidance for [spawning .bat and .cmd files](https://nodejs.org/docs/latest-v24.x/api/child_process.html#spawning-bat-and-cmd-files-on-windows), while avoiding `shell: true` with `args[]`, which is what [DEP0190](https://nodejs.org/download/release/latest/docs/api/deprecations.html#dep0190-passing-args-to-nodechild_process-execfilespawn-with-shell-option-true) warns about.

So this seems like a solid approach to me.
