### PR TITLE
chore: fix spelling & grammar

### LINKED ISSUE #2650: Spelling errors
### Describe the bug

I ran a tool and identified some spelling / grammar errors

### Additional context

https://github.com/jsoref/npmx.dev/actions/runs/25090112762/attempts/1#summary-73514231617

### Logs

```shell-script
Steps:
1. Add https://github.com/jsoref/npmx.dev/commit/ca3fcc789e2f2304f1beff49aae62e1b4094b5e7 to the repository
2. Review the output
```

### PR DESCRIPTION
**Pull request by jsoref**
### 🔗 Linked issue

- resolves #2650

### 🧭 Context

spelling errors harm many aspects

### 📚 Description

each fix is standalone and easy to understand

### CODE REVIEW

File: app/components/Noodle/index.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@ export type Noodle = {
   timezone?: string
   // Date for the noodle
   date?: string
-  // Date to for the noodle
+  // `Date to` for the noodle
```
Comment (jsoref) [inline app/components/Noodle/index.ts:12]: While `Date for the noodle` reads properly in English, `Date to for the noodle` really doesn't. I'm suggesting adding `` ` `` to make it readable...

File: cli/src/mock-server.ts [hunk 2]
```diff
@@ -1,6 +1,6 @@
 #!/usr/bin/env node
 /**
- * Mock connector CLI — starts a pre-populated mock server for developing
+ * Mock connector CLI — starts a prepopulated mock server for developing
```
Comment (jsoref) [inline cli/src/mock-server.ts:3]: I'm making this suggestion because the CONTRIBUTING guide uses the `en-US` flavor for `Prerequisites`:
https://github.com/npmx-dev/npmx.dev/blob/17ea220a8ca9a0d6831c3afe43520649bdf4f709/CONTRIBUTING.md?plain=1#L30

(It's mostly an outlier in that regard -- the rest of the project feels like it's en-GB, but I'm favoring contributing since I was expected to read it.)

File: server/api/registry/org/[org]/packages.get.ts [hunk 3]
```diff
@@ -1,7 +1,7 @@
 import { CACHE_MAX_AGE_ONE_HOUR, NPM_REGISTRY } from '#shared/utils/constants'
 import { FetchError } from 'ofetch'
 
-// Validation pattern for npm org names - url-sage symbold and not start with a dot (incl. ~test24214. or -ex~-)
+// Validation pattern for npm org names - url-sage symbol and not start with a dot (incl. ~test24214. or -ex~-)
```
Comment (jsoref) [inline server/api/registry/org/[org]/packages.get.ts:4]: It's possible that `symbold` is intentional, but there wasn't any obvious support for it...

**Review by graphieros — CHANGES_REQUESTED** [review]
Thank you!
Can you apply that remaining suggestion from CodeRabbit ?

**Review by graphieros — APPROVED** [review]
LGTM 🌿

File: server/api/registry/org/[org]/packages.get.ts (hunk 3 above)
Comment (gameroman) [inline server/api/registry/org/[org]/packages.get.ts:4]: Should that also be `url-safe`?

```suggestion
// Validation pattern for npm org names - url-safe symbol and not start with a dot (incl. ~test24214. or -ex~-)
```

Comment (jsoref) [reply server/api/registry/org/[org]/packages.get.ts:4]: That certainly makes more sense.

Comment (jsoref) [reply server/api/registry/org/[org]/packages.get.ts:4]: https://github.com/npmx-dev/npmx.dev/pull/2655/changes/b603393c7a15079b2ad3073d9fc99b20c7f08594
