### PR TITLE
fix: blank page when javascript is disabled

### LINKED ISSUE #1291: package page doesn't load with javascript disabled
It doesn't work at all without javascript and before it was working

### PR DESCRIPTION
**Pull request by NandkishorJadoun**
resolves #1291 

## Description

This pr adds a nitro server plugin that injects a `<meta http-equiv="refresh">` tag specifically into the SPA fallback shell (`200.html`), wrapped in a `<noscript>` block.

### CODE REVIEW

**Comment by NandkishorJadoun** [comment]
@danielroe , should i reduce the delay to 0 seconds? im concerned that might trigger an infinite loop, though I'm not entirely sure. i've set it to 1 second for now to be safe

**Comment by ghostdevv** [comment]
cc: @LoryPelli

**Comment by danielroe** [comment]
we may need to disable the validator on 200.html

on the other hand, I think setting to 0 should be safe.

File: server/plugins/fallback-ui.ts [hunk 1]
```diff
@@ -0,0 +1,7 @@
+export default defineNitroPlugin(nitroApp => {
+  nitroApp.hooks.hook('render:html', (html, { event }) => {
+    if (event.path.includes('/200.html')) {
+      html.head.push('<noscript><meta http-equiv="refresh" content="1"></noscript>')
```
Comment (danielroe) [inline server/plugins/fallback-ui.ts]:
```suggestion
      html.head.push('<noscript><meta http-equiv="refresh" content="0"></noscript>')
```
