### PR TITLE
fix: semver sorting

### LINKED ISSUE #139: versions aren't quite sorted per SemVer spec
Check out https://semver.org/#spec-item-11.

Example: https://npmx.dev/next (expand "Other versions")

Image

Numeric segments should be compared numerically, not alphanumerically.

### PR DESCRIPTION
**Pull request by MatteoGabriele**
Uses the built-in compare method from the `semver` package.

before
Screenshot 2026-01-26 at 20 46 20

after
Screenshot 2026-01-26 at 20 45 44

closes #139

### CODE REVIEW

File: app/utils/versions.ts [hunk 1]
```diff
@@ -47,19 +47,7 @@ export function parseVersion(version: string): ParsedVersion {
  * @returns Comparison result for sorting
  */
 export function compareVersions(a: string, b: string): number {
```
Comment (danielroe) [inline app/utils/versions.ts]: can we just use compare wherever compareVersions is used instead of wrapping it?

Comment (MatteoGabriele) [reply app/utils/versions.ts]: Definitely! I thought about keeping the wrapper for future changes, but it's indeed cleaner to use the package's method where needed, which also eliminates the need for tests.
