### PR TITLE
fix(ui): hide awkward empty state for weekly downloads for new packages

### LINKED ISSUE #1044: Awkward empty state for weekly downloads section
In case of new packages that do not have any weekly downloads just yet, the following chart is shown:

Image

An empty chart with no data on neither X or Y axis.

In such cases, npmjs.com just hides the chart.

### PR DESCRIPTION
**Pull request by wojtekmaj**
Closes #1044

Too new packages now have Weekly downloads hidden:

image

Well established packages of course still have the section:

image

### CODE REVIEW

File: app/components/Package/WeeklyDownloadStats.vue [hunk 1]
```diff
@@ -85,10 +87,13 @@ const pulseColor = computed(() => {
 })
 
 const weeklyDownloads = shallowRef<WeeklyDownloadPoint[]>([])
+const isLoadingWeeklyDownloads = shallowRef(false)
```
[the remark this answers is not in the document]
Comment (wojtekmaj) [reply app/components/Package/WeeklyDownloadStats.vue]: Sure

**Comment by serhalp** [comment]
My hunch is it's more confusing to hide this entirely. We might get future bug reports like "the downloads chart is missing". Could we keep just the heading and show "No downloads yet"? 🤔

**Comment by wojtekmaj** [comment]
> My hunch is it's more confusing to hide this entirely. We might get future bug reports like "the downloads chart is missing". Could we keep just the heading and show "No downloads yet"? 🤔

Good idea, I'll do this today

File: app/components/Package/WeeklyDownloadStats.vue [hunk 2]
```diff
@@ -212,44 +221,52 @@ const config = computed(() => {
...
-              <!-- Title row: date range (24px height) -->
-              <div class="h-6 flex items-center ps-3">
-                <SkeletonInline class="h-3 w-36" />
-              </div>
-              <!-- Chart area: data label left, sparkline right -->
-              <div class="aspect-[500/80] flex items-center">
-                <!-- Data label (covers ~42% width) -->
-                <div class="w-[42%] flex items-center ps-0.5">
-                  <SkeletonInline class="h-7 w-24" />
+        <template v-if="isLoadingWeeklyDownloads || hasWeeklyDownloads">
```
Comment (43081j) [inline app/components/Package/WeeklyDownloadStats.vue:234]: does this mean if we're loading the downloads but ultimately have none in the end, we'll flash the chart up then remove it?

Comment (wojtekmaj) [reply app/components/Package/WeeklyDownloadStats.vue:234]: I guess we're optimistically assuming it WILL load, as it does for 99,9% of cases

**Comment by 43081j** [comment]
also agree we should show a "no data" message or something instead, like a subtle overlay of some sort

i see you're already planning on changing it so will re-review once you push 👍

**Comment by ghostdevv** [comment]
(marked as draft while you're making changes)

**Review by serhalp — APPROVED** [review]
🎉
