### PR TITLE
fix: preserve backtick spans in markdown

### LINKED ISSUE #1478: Short description text not getting escaped correctly
Seems like the short description text isn't getting escape properly, whereas the actual readme text does get rendered as intended:

Image

### PR DESCRIPTION
**Pull request by vmrjnvc**
### 🔗 Linked issue

Resolves #1478 

### 📚 Description

This update fixes an issue with package descriptions containing code snippets wrapped in backticks. Previously, the HTML stripping function removed HTML tags no matter if they were wrapped with backticks. Because of that short description of packages was broken when code snippets with html tags were processed.

### CODE REVIEW

File: app/composables/useMarkdown.ts [hunk 1]
```diff
@@ -32,12 +33,19 @@ function stripAndEscapeHtml(text: string, packageName?: string): string {
...
+  // Strip actual HTML tags (keep their text content), but leave tags inside backtick spans
+  // The alternation matches a backtick span first — if that branch wins the match is kept as-is
+  stripped = stripped.replace(
+    /(`[^`]*`)|<\/?[a-z][^>]*>/gi,
+    (match, codeSpan: string | undefined) => codeSpan ?? '',
+  )
 
   // Strip HTML comments: <!-- ... --> (including unclosed comments from truncation)
-  stripped = stripped.replace(/<!--[\s\S]*?(-->|$)/g, '')
+  // Same alternation trick: preserve backtick spans so comments inside code are kept
```
Comment (danielroe) [inline app/composables/useMarkdown.ts]:
```suggestion
  // Strip HTML comments: <!-- ... --> (including unclosed comments from truncation)
```

File: app/composables/useMarkdown.ts [hunk 2]
```diff
@@ -32,12 +33,19 @@ function stripAndEscapeHtml(text: string, packageName?: string): string {
...
+  // Strip actual HTML tags (keep their text content), but leave tags inside backtick spans
+  // The alternation matches a backtick span first — if that branch wins the match is kept as-is
+  stripped = stripped.replace(
+    /(`[^`]*`)|<\/?[a-z][^>]*>/gi,
+    (match, codeSpan: string | undefined) => codeSpan ?? '',
+  )
 
   // Strip HTML comments: <!-- ... --> (including unclosed comments from truncation)
-  stripped = stripped.replace(/<!--[\s\S]*?(-->|$)/g, '')
+  // Strip HTML comments: <!-- ... --> (including unclosed comments from truncation)
```
Comment (danielroe) [inline app/composables/useMarkdown.ts:43]:
```suggestion
```
