### PR TITLE
fix: fix zindex issue of button in header

### LINKED ISSUE #2074: Visual issues with recently reworked package header
### Describe the bug

1. Version selector `z-index` conflicts with header dropdown
<details>
<summary>Screenshot</summary>

Image
</details>

2. Copy version button is hidden behind other buttons and not clickable
<details>
<summary>Screenshot</summary>

Image
</details>

3. Compare and like button outline is hidden behind next div
<details>
<summary>Screenshot</summary>
Image
</details>

4. Tabs outline looks broken (just 1 line is visible)
<details>
<summary>Screenshot</summary>
Image
</details>

### PR DESCRIPTION
**Pull request by ShroXd**
### 🔗 Linked issue

Resolves #2074 

### 🧭 Context

`CopyToClipboardButton` is hidden behind the header. This PR fixes it.

FYI @alexdln 

### 📚 Description

This button is also used in the compare page where it works fine, so the fix is applied locally rather than changing the z-index in the button component itself.

| Scenario | Screenshot |
| :- | :- |
| Copy button | fixed-zindex |
| Connect | QQ20260316-104619 |
| Outline of _compare_ button | QQ20260316-104731 |
| Outline of active menu | QQ20260316-104720 |
| Outline of non-active menu | QQ20260316-104704 |

### CODE REVIEW

File: app/components/Package/Header.vue [hunk 1]
```diff
@@ -453,6 +453,10 @@ const likeAction = async () => {
   display: none;
 }
 
+.packageNav > :global(a:focus-visible) {
+  outline-offset: -2px !important;
+}
```
Comment (alexdln) [inline app/components/Package/Header.vue]: Could you please add Tailwind classes where needed instead of this override?

Comment (ShroXd) [reply app/components/Package/Header.vue]: > Could you please add Tailwind classes where needed instead of this override?

Thanks for pointing it out! I have refactored the code.

**Comment by alexdln** [comment]
Perfect, thank you ❤️
