### PR TITLE
fix(blog): ui improvements and comment layout fix

### LINKED ISSUE #2136: Blog ui improvements
We need to make some UI adjustments on our blog pages (i.e. https://npmx.dev/blog/alpha-release)

1. Fix indents. It should match the header container. On desktop it should also match the authors container

Image

2. Fix colors on hover for bluesky buttons

Image

3. Fix bluesky icon position - it should be at the same distance from the left and top corners

Image

4. Add hover effects for internal links (follow package styles)

Image

### LINKED ISSUE #2137: Fix nested comments on blog
With deeply nested comments on blog (https://npmx.dev/blog/alpha-release), we experience horizontal scrolling on mobile. Ideally, we should reduce the space between comments, but this would require reworking the markup (_currently, it's set to match the avatar width_)

Image

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
## Summary

- Reduced spacing in nested comments on mobile
- Fixed blog content indentation alignment with header/authors
- Fixed button-primary hover states in light mode
- Fixed Bluesky embed icon positioning (equidistant from top/right edges)
- Added hover effects for blog prose links
- Reduced federated articles' hover shadow intensity
- Fixed federated articles mobile alignment

Closes #2136, closes #2137

### CODE REVIEW

File: app/components/global/BlogPostFederatedArticles.vue [hunk 1]
```diff
@@ -55,7 +55,7 @@ const federatedArticles = computed(() => {
         rel="noopener noreferrer"
         v-for="article in federatedArticles"
         :key="article.url"
-        class="grid grid-cols-[auto_1fr] gap-x-5 no-underline hover:no-underline rounded-lg border border-border p-4 transition-shadow hover:shadow-lg hover:shadow-gray-500/50"
+        class="grid grid-cols-[auto_1fr] gap-x-5 no-underline hover:no-underline rounded-lg border border-border p-4 transition-all hover:shadow-md hover:shadow-black/5 dark:hover:shadow-white/5 hover:border-border-hover"
```
Comment (alexdln) [inline app/components/global/BlogPostFederatedArticles.vue]: how about


```suggestion
        class="grid grid-cols-[auto_1fr] gap-x-5 no-underline hover:no-underline rounded-lg border border-border p-4 transition-all hover:shadow-md hover:shadow-fg/5 hover:border-border-hover"
```

File: app/components/global/BlogPostWrapper.vue [hunk 2]
```diff
@@ -77,4 +77,19 @@ const blueskyPostUri = computed(() => blueskyLink.value?.postUri ?? null)
...
+
+:deep(.prose a:not(.not-prose a)) {
+  text-decoration: underline;
+  text-underline-offset: 0.2rem;
+  text-decoration-thickness: 1px;
+  text-decoration-color: var(--fg-subtle);
+  transition:
+    text-decoration-color 0.2s,
+    color 0.2s;
+}
```
Comment (alexdln) [inline app/components/global/BlogPostWrapper.vue]: Affected all the links on the page, including bsky embeds and related articles

File: app/components/global/BlueskyPostEmbed.client.vue [hunk 3]
```diff
@@ -107,10 +107,16 @@ const postUrl = computed(() => {
...
     target="_blank"
     rel="noopener noreferrer"
-    class="not-prose block rounded-lg border border-border bg-bg-subtle p-4 sm:p-5 no-underline hover:border-border-hover transition-colors duration-200"
+    class="not-prose block rounded-lg border border-border bg-bg-subtle p-4 sm:p-5 no-underline hover:border-border-hover transition-colors duration-200 relative"
   >
+    <!-- Bluesky icon -->
+    <span
+      class="i-simple-icons:bluesky w-5 h-5 text-fg-subtle absolute top-4 end-4 sm:top-5 sm:end-5"
+      aria-hidden="true"
+    />
```
Comment (alexdln) [inline app/components/global/BlueskyPostEmbed.client.vue]: wdyt about add `group` to the whole embed and change icon color on hover on the card


```suggestion
    class="not-prose block rounded-lg border border-border bg-bg-subtle p-4 sm:p-5 no-underline hover:border-border-hover transition-colors duration-200 relative group"
>
    <!-- Bluesky icon -->
    <span
      class="i-simple-icons:bluesky w-5 h-5 text-fg-subtle group-hover:text-blue-500 absolute top-4 end-4 sm:top-5 sm:end-5"
      aria-hidden="true"
    />
```

(not sure about the color)

File: app/components/Link/Base.vue [hunk 4]
```diff
@@ -101,7 +101,7 @@ const keyboardShortcutsEnabled = useKeyboardShortcuts()
       'text-xs px-2 py-0.5': isButtonSmall,
       'bg-transparent text-fg hover:(bg-fg/10 text-accent) focus-visible:(bg-fg/10 text-accent) aria-[current=true]:(bg-fg/10 text-accent border-fg/20 hover:enabled:(bg-fg/20 text-fg/50))':
         variant === 'button-secondary',
-      'text-bg bg-fg hover:(bg-fg/50 text-accent) focus-visible:(bg-fg/50) aria-current:(bg-fg text-bg border-fg hover:enabled:(text-bg/50))':
+      'text-bg bg-fg hover:(bg-fg/80 text-bg) focus-visible:(bg-fg/80 text-bg) aria-current:(bg-fg text-bg border-fg hover:enabled:(text-bg/50))':
         variant === 'button-primary',
```
Comment (alexdln) [inline app/components/Link/Base.vue]: Feels like it can affect us in unexpected place. Can we keep accent color for now or is there any reason for such a change in global component?

File: app/components/BlueskyComment.vue [hunk 5]
```diff
@@ -41,13 +41,17 @@ function getHostname(uri: string): string {
...
+    Depth 1+: Medium-style inline avatar on mobile, avatar-column on desktop
+  -->
+  <div :class="depth === 0 ? 'flex gap-3' : 'sm:flex sm:gap-3'">
+    <!-- Column avatar: always shown at depth 0, desktop-only at depth 1+ -->
     <a
       :href="`https://bsky.app/profile/${comment.author.handle}`"
       target="_blank"
       rel="noopener noreferrer"
-      class="shrink-0"
+      :class="['shrink-0', depth > 0 ? 'hidden sm:block' : '']"
```
Comment (alexdln) [inline app/components/BlueskyComment.vue]:
```suggestion
      class="shrink-0"
      :class="depth > 0 ? 'hidden sm:block' : '"
```

File: app/components/BlueskyComment.vue [hunk 6]
```diff
@@ -71,16 +76,39 @@ function getHostname(uri: string): string {
...
+            class="w-6 h-6 rounded-full"
+            width="24"
+            height="24"
+            loading="lazy"
+          />
+          <div
+            v-else
+            class="w-6 h-6 rounded-full bg-border flex items-center justify-center text-fg-muted text-xs"
+          >
+            {{ (comment.author.displayName || comment.author.handle).charAt(0).toUpperCase() }}
```
Comment (ghostdevv) [inline app/components/BlueskyComment.vue]: this is probably me trying to solve a problem that doesn't exist yet, but this is a more reliable way of getting the first char as it handles unicode chars that are made up of multiple points.

```ts
function first(str: string) {
	const segmenter = new Intl.Segmenter({ granularity: 'grapheme' });
	return Array.from(segmenter.segment(str))[0]?.segment;
}
```

Comment (Adebesin-Cell) [reply app/components/BlueskyComment.vue]: 😄 That's fine! 
I got to use `Intl.Segment` in a production code for the first time 😅. I made the changes in [`520a5df` (this PR)](https://github.com/npmx-dev/npmx.dev/pull/2139/commits/520a5df9e1fa9a2d81d38420af5735ac0d27ed15)

Comment (ghostdevv) [reply app/components/BlueskyComment.vue]: I pushed a small optimisation I missed, probably won't matter here but still :p

https://github.com/npmx-dev/npmx.dev/pull/2139/changes/e1aaaa7db4308f57a292a6edabc93e2dda8e62dc

**Comment by ghostdevv** [comment]
Looks like the comments have been addressed! We can do a follow up if we missed anything :pray:
