### PR TITLE
fix: filter out security holding packages from Algolia results

### LINKED ISSUE #2002: ⚠️ Algolia search returns malicious/dangerous packages removed from npm registry search
### Describe the feature

While working on another search-related topic https://github.com/npmx-dev/npmx.dev/pull/1996 I've found that Algolia returns packages, which are basically ad for download stolen e-books. It appears that npm already marked these packages as malicious.

Example (marked as "Security holding package"):
https://npmx.dev/package/dowload_ebok_voir_grand_by_luc_poirier_bdn67
https://www.npmjs.com/package/dowload_ebok_voir_grand_by_luc_poirier_bdn67
https://registry.npmjs.org/dowload_ebok_voir_grand_by_luc_poirier_bdn67

Example similar but **NOT** marked as dangerous:
https://npmx.dev/package/dowload_ebok_bone_t01_by_jeff_smith_g9wli
https://www.npmjs.com/package/dowload_ebok_bone_t01_by_jeff_smith_g9wli
https://registry.npmjs.org/dowload_ebok_bone_t01_by_jeff_smith_g9wli

NPM also filters out packages that looks similar, but not yet marked as "security holding", but Algolia search returns it.

Algolia result for `"download_ebook"`:
https://npmx.dev/search?q=dowload_ebook

npm search result:
https://npmx.dev/search?q=download_ebook&p=npm
https://registry.npmjs.org/-/v1/search?text=download_ebook&size=10

npmjs.org:
https://www.npmjs.com/search?q=dowload_ebook

Image

Image

To discuss:
- add internal logic to detect malicious packages and mark in UI when entered by direct link (similar to e18e issues). Maybe shold be part of e18e
- add internal filtering of Algolia results to remove such packages

### Additional information

- [x] Would you be willing to help implement this feature?

### Final checks

- [x] Read the [contribution guide](https://github.com/npmx-dev/npmx.dev/blob/main/CONTRIBUTING.md).
- [x] Check existing [issues](https://github.com/npmx-dev/npmx.dev/issues).

### PR DESCRIPTION
**Pull request by shuuji3**
### 🔗 Linked issue

resolves #2002
### 🧭 Context

Algoria search returns packages already takendown by npm registory and marked as "Security holding package".

### 📚 Description

- Filter out packages where the package's version is `0.0.1-security` AND its description is `security holding package`.
  - It seems that this is npm's hardcoded values though I couldn't find official docs that describe this.
  - It could be false positive but it's unlike someone uses these value combination.

- You can compare:
  - https://npmx.dev/search?q=download_ebook
  - https://npmxdev-git-shuuji3-fixfilter-out-security-holding-51982d-npmx.vercel.app/search?q=download_ebook

- Example returned value from algoria search API (from network tab):
```json
{
	"results": [
		{
			"hits": [
				{
					"name": "dowload_ebok_grundkurs_kunstliche_intelligenz_by_wolfgang_ertel_r9sfy",
					"downloadsLast30Days": 0,
					"downloadsRatio": 0,
					"popular": false,
					"version": "0.0.1-security",
					"description": "security holding package",
					"repository": {
						"type": "git",
						"url": "npm/security-holder",
						"project": "security-holder",
						"user": "npm",
						"host": "github.com",
						"path": "",
						"branch": "master"
					},
					"deprecated": false,
					"isDeprecated": false,
					"homepage": null,
					"license": null,
					"keywords": [],
					"modified": 1758520468387,
					"owners": [],
					"objectID": "dowload_ebok_grundkurs_kunstliche_intelligenz_by_wolfgang_ertel_r9sfy"
				},
				{
					"name": "dowload_ebok_farouche_atalante_by_emilie_druilhe_nx2bj",
					"downloadsLast30Days": 0,
					"downloadsRatio": 0,
					"popular": false,
					"version": "0.0.1-security",
					"description": "security holding package",
					"repository": {
						"type": "git",
						"url": "npm/security-holder",
						"project": "security-holder",
						"user": "npm",
						"host": "github.com",
						"path": "",
						"branch": "master"
					},
					"deprecated": false,
					"isDeprecated": false,
					"homepage": null,
					"license": null,
					"keywords": [],
					"modified": 1725351874194,
					"owners": [],
					"objectID": "dowload_ebok_farouche_atalante_by_emilie_druilhe_nx2bj"
				},
				{
					"name": "dowload_ebok_everything_in_between_a_rocker_romance_by_melissa_toppen_fp7ge",
					"downloadsLast30Days": 0,
					"downloadsRatio": 0,
					"popular": false,
					"version": "0.0.1-security",
					"description": "security holding package",
					"repository": {
						"type": "git",
						"url": "npm/security-holder",
						"project": "security-holder",
						"user": "npm",
						"host": "github.com",
						"path": "",
						"branch": "master"
					},
					"deprecated": false,
					"isDeprecated": false,
					"homepage": null,
					"license": null,
					"keywords": [],
					"modified": 1725351869604,
					"owners": [],
					"objectID": "dowload_ebok_everything_in_between_a_rocker_romance_by_melissa_toppen_fp7ge"
				},
				{
					"name": "dowload_ebok_englens_spil_by_carlos_ruiz_zafon_iben_hasselbalch_lqvq8",
					"downloadsLast30Days": 0,
					"downloadsRatio": 0,
					"popular": false,
					"version": "0.0.1-security",
					"description": "security holding package",
					"repository": {
						"type": "git",
						"url": "npm/security-holder",
						"project": "security-holder",
						"user": "npm",
						"host": "github.com",
						"path": "",
						"branch": "master"
					},
					"deprecated": false,
					"isDeprecated": false,
					"homepage": null,
					"license": null,
					"keywords": [],
					"modified": 1745588033919,
					"owners": [],
					"objectID": "dowload_ebok_englens_spil_by_carlos_ruiz_zafon_iben_hasselbalch_lqvq8"
				},
				{
					"name": "dowload_ebok_before_dawn_vampire_fallen_book_1_by_morgan_rice_fjwc4",
					"downloadsLast30Days": 0,
					"downloadsRatio": 0,
					"popular": false,
					"version": "0.0.1-security",
					"description": "security holding package",
					"repository": {
						"type": "git",
						"url": "npm/security-holder",
						"project": "security-holder",
						"user": "npm",
						"host": "github.com",
						"path": "",
						"branch": "master"
					},
					"deprecated": false,
					"isDeprecated": false,
					"homepage": null,
					"license": null,
					"keywords": [],
					"modified": 1762128250838,
					"owners": [],
					"objectID": "dowload_ebok_before_dawn_vampire_fallen_book_1_by_morgan_rice_fjwc4"
				},
				{
					"name": "dowload_ebok_a_guerra_de_hitler_e_o_horror_do_holocausto_by_scott_s_f_meaker_k644u",
					"downloadsLast30Days": 0,
					"downloadsRatio": 0,
					"popular": false,
					"version": "0.0.1-security",
					"description": "security holding package",
					"repository": {
						"type": "git",
						"url": "npm/security-holder",
						"project": "security-holder",
						"user": "npm",
						"host": "github.com",
						"path": "",
						"branch": "master"
					},
					"deprecated": false,
					"isDeprecated": false,
					"homepage": null,
					"license": null,
					"keywords": [],
					"modified": 1762128244458,
					"owners": [],
					"objectID": "dowload_ebok_a_guerra_de_hitler_e_o_horror_do_holocausto_by_scott_s_f_meaker_k644u"
				},
				{
					"name": "dowload_ebok_a_bela_e_a_fera_by_elizabeth_rudnick_evan_spiliotopoulos_stephen_ch_9ooey",
					"downloadsLast30Days": 0,
					"downloadsRatio": 0,
					"popular": false,
					"version": "0.0.1-security",
					"description": "security holding package",
					"repository": {
						"type": "git",
						"url": "npm/security-holder",
						"project": "security-holder",
						"user": "npm",
						"host": "github.com",
						"path": "",
						"branch": "master"
					},
					"deprecated": false,
					"isDeprecated": false,
					"homepage": null,
					"license": null,
					"keywords": [],
					"modified": 1745588028183,
					"owners": [],
					"objectID": "dowload_ebok_a_bela_e_a_fera_by_elizabeth_rudnick_evan_spiliotopoulos_stephen_ch_9ooey"
				},
				{
					"name": "dowload_ebok_1917_une_passion_russe_by_max_gallo_d2xeh",
					"downloadsLast30Days": 0,
					"downloadsRatio": 0,
					"popular": false,
					"version": "0.0.1-security",
					"description": "security holding package",
					"repository": {
						"type": "git",
						"url": "npm/security-holder",
						"project": "security-holder",
						"user": "npm",
						"host": "github.com",
						"path": "",
						"branch": "master"
					},
					"deprecated": false,
					"isDeprecated": false,
					"homepage": null,
					"license": null,
					"keywords": [],
					"modified": 1758520462981,
					"owners": [],
					"objectID": "dowload_ebok_1917_une_passion_russe_by_max_gallo_d2xeh"
				}
			],
			"nbHits": 28,
			"offset": 20,
			"length": 8,
			"exhaustiveNbHits": false,
			"exhaustiveTypo": false,
			"exhaustive": {
				"nbHits": false,
				"typo": false
			},
			"query": "download_ebook",
			"params": "query=download_ebook&offset=20&length=8&analyticsTags=%5B%22npmx.dev%22%5D&attributesToRetrieve=%5B%22name%22%2C%22version%22%2C%22description%22%2C%22modified%22%2C%22homepage%22%2C%22repository%22%2C%22owners%22%2C%22downloadsLast30Days%22%2C%22downloadsRatio%22%2C%22popular%22%2C%22keywords%22%2C%22deprecated%22%2C%22isDeprecated%22%2C%22license%22%5D&attributesToHighlight=%5B%5D",
			"index": "npm-search",
			"processingTimeMS": 27,
			"processingTimingsMS": {
				"_request": {
					"roundTrip": 5
				},
				"fetch": {
					"query": 17,
					"scanning": 6,
					"total": 24
				},
				"getIdx": {
					"load": {
						"total": 1
					},
					"total": 1
				},
				"total": 27
			},
			"serverTimeMS": 28
		}
	]
}
```

### CODE REVIEW

**Comment by alexdln** [comment]
@shuuji3 Maybe it's better to check only `repository.url !== "npm/security-holder"`?

**Comment by shuuji3** [comment]
@alexdln Right, probably that's simpler and rubust. I thought repository information might not exist, but I now thing it's unlikely in this case.

**Comment by serhalp** [comment]
@shuuji3 🤔 hmm, it doesn't seem to be filtering them out. in any case, maybe we should add test coverage for this?

**Comment by shuuji3** [comment]
I found that Algoria API actually has the exact attribute for the security holding pakcages called `isSecurityHeld` so there was no need to implement ourselves. I abondoned my initial implementation and change to include that attribute in the API response.

I also added tests for `useAlgoliaSearch` composable.

File: app/pages/search.vue [hunk 1]
```diff
@@ -86,14 +86,17 @@ const { settings } = useSettings()
...
+ * and optionally filter out platform-specific packages or security holding packages.
  */
 const visibleResults = computed(() => {
   const raw = rawVisibleResults.value
   if (!raw) return raw
 
   let objects = raw.objects
 
+  // Filter out "Security holding package" packages taken down by npm registry
+  objects = objects.filter(r => !r.package.isSecurityHeld)
```
Comment (serhalp) [inline app/pages/search.vue:98]: 💭 Wouldn't it be preferable to implement this filtering in the `useAlgoliaSearch` or `useGlobalSearch` composable? Otherwise we'd still be showing security holding packages in other places we use search today (compare page typeahead) and in the future.

**Review by serhalp — APPROVED** [review]
LGTM, good find!

File: app/pages/search.vue (hunk 1 above)
Comment (serhalp) [reply app/pages/search.vue:98]: I'm going to merge this since it's a somewhat important fix, but I think this is worth considering as a follow-up refactor!

Comment (shuuji3) [reply app/pages/search.vue:98]: @serhalp Thanks, I think `useAlgoliaSearch` would be a proper location to add filter since the npm API returns the pre-filtered package list so we can make both consistent. I'll create a follow-up PR when I found time later 🙏🏻
